export const BUSINESS = {
  name: 'MB Auto Collective',
  director: 'Matt',
  phone: '0400 003 994',
  phoneHref: 'tel:+61400003994',
  whatsappHref: 'https://wa.me/61400003994',
  email: 'matt@mbautocollective.com',
  address: '1/267 Young Street, Waterloo NSW 2017',
  mapsUrl: 'https://maps.app.goo.gl/4UTj9iU3cf6JrDpr5',
  abn: '44 637 706 953',
  licence: 'MD081672',
  reviewCount: 126,
  reviewScore: '5.0',
  tagline: 'Buy. Sell. Drive.',
  domain: 'mbautocollective.com',
  siteUrl: 'https://mbautocollective.com',
} as const;

export const GOOGLE_REVIEWS = [
  {
    text: "Couldn't speak more highly of the service Matt offers. Knows the business inside out and stopped at nothing until we found the car we were after.",
    author: 'Edward Simpson',
    stars: 5,
  },
  {
    text: "Matt has been fantastic from start to finish. I thought customer service wasn't a thing anymore but these guys go above and beyond.",
    author: 'William Killen',
    stars: 5,
  },
  {
    text: 'I had an amazing experience from start to finish with Matt. He was welcoming, professional, and very knowledgeable. All their cars look in showroom condition.',
    author: 'Vince Rocs',
    stars: 5,
  },
  {
    text: "The best car buying experience ever. Matt was beyond helpful and none of my questions were too dumb. I love my car!",
    author: 'Sheona Devin',
    stars: 5,
  },
  {
    text: 'Purchased a Cupra and had it sent to Perth. Matt made the whole process super simple. Car arrived just as good as promised.',
    author: 'Kyle',
    stars: 5,
  },
  {
    text: 'Matt made the experience so easy. A one stop shop and a five star service. I would recommend MB Auto Collective to anyone.',
    author: 'Brian Meadows',
    stars: 5,
  },
] as const;

export const BODY_TYPES = ['Sedan', 'SUV', 'Coupé', 'Convertible', 'Wagon', 'Hatchback', 'Ute'] as const;
export const TRANSMISSIONS = ['Automatic', 'Manual'] as const;
export const FUEL_TYPES = ['Petrol', 'Diesel', 'Hybrid', 'Electric'] as const;
export const STATUSES = ['available', 'reserved', 'sold'] as const;

export const FEATURE_CATEGORIES = [
  {
    label: 'Safety & Driver Assistance',
    features: [
      'Anti-Lock Braking (ABS)',
      'Brake Assist',
      'Electronic Brake Force Distribution (EBD)',
      'Electronic Stability Program (ESP)',
      'Traction Control',
      'Automatic Emergency Braking (AEB)',
      'Forward Collision Warning',
      'Lane Departure Warning',
      'Lane Keep Assist',
      'Blind Spot Monitoring',
      'Rear Cross Traffic Alert',
      'Adaptive Cruise Control',
      'Cruise Control',
      'Driver Fatigue Detection',
      'Reversing Camera',
      'Front Parking Sensors',
      'Rear Parking Sensors',
      '360-Degree Camera',
      'Heads-Up Display',
      'Auto High Beam',
      'Dual Front Airbags',
      'Side Airbags',
      'Curtain Airbags',
      'Knee Airbag - Driver',
      'Child Seat Anchor Points',
      'Child Seat - ISOFIX',
      'Emergency Call Button',
      'Automatic Collision Notification',
      'Alarm System / Remote Anti-Theft',
      'Immobiliser',
      'Hill Start Assist',
      'Hill Descent Control',
    ],
  },
  {
    label: 'Comfort & Convenience',
    features: [
      'Automatic Air Con / Climate Control',
      'Dual-Zone Climate Control',
      'Multi-Zone Climate Control',
      'Heated Front Seats',
      'Ventilated / Cooled Front Seats',
      'Heated Rear Seats',
      'Power-Adjustable Driver Seat',
      'Power-Adjustable Passenger Seat',
      'Adjustable Front Seats - Manual',
      'Memory Seat - Driver',
      'Adjustable Steering Wheel - Tilt & Telescopic',
      'Keyless Entry',
      'Push-Button Start',
      'Central Locking Remote Control',
      'Power Windows',
      'Power Mirrors',
      'Folding Mirrors',
      'Heated Mirrors',
      'Auto-Dimming Rear-View Mirror',
      'Rain-Sensing Wipers',
      'Dusk-Sensing Headlights',
      'Sunroof',
      'Panoramic Sunroof',
      'Multi-Function Steering Wheel',
      'Paddle Shifters',
      'Power Boot / Tailgate',
      'Hands-Free Tailgate',
      'Remote Engine Start',
    ],
  },
  {
    label: 'Entertainment & Connectivity',
    features: [
      'Bluetooth Connectivity',
      'Apple CarPlay',
      'Android Auto',
      'Wireless Apple CarPlay / Android Auto',
      'DAB+ Digital Radio',
      'Satellite Navigation',
      'Touchscreen Infotainment',
      'Premium / Upgraded Sound System',
      'Aux / USB Input',
      'Wireless Phone Charging',
      'Wi-Fi Hotspot',
      'Connect App Services',
      'Digital Clock',
      'Head Unit Upgrade',
      'Multi-Zone Audio',
      'Rear Seat Entertainment',
    ],
  },
  {
    label: 'Exterior',
    features: [
      '17 Inch Alloy Wheels',
      '18 Inch Alloy Wheels',
      '19 Inch Alloy Wheels',
      '20 Inch Alloy Wheels',
      '21 Inch Alloy Wheels',
      '22 Inch Alloy Wheels',
      'LED Headlights',
      'LED Daytime Running Lights',
      'Xenon / HID Headlights',
      'Adaptive Headlights',
      'Fog Lights',
      'Shark Fin Antenna',
      'Chrome Exterior Door Handles',
      'Black Exterior Door Handles',
      'Chrome Front Grille',
      'Black Front Grille',
      'Tinted Windows',
      'Privacy Glass',
      'Power Sunroof',
      'Panoramic Glass Roof',
      'Side Steps / Running Boards',
      'Roof Rails',
      'Roof Rack',
      'Tow Bar',
      'Bull Bar',
      'Nudge Bar',
      'Sports Bar (Ute)',
      'Alloy Sports Bar',
      'Hard Lid / Tonneau Cover',
      'Sports Exhaust',
    ],
  },
  {
    label: 'Interior',
    features: [
      'Leather Trim',
      'Leather-Accented Trim',
      'Cloth Trim',
      'Alcantara / Suede Trim',
      'Carpet Floor Covering',
      'All-Weather Floor Mats',
      'Centre Console Box - Multi-Purpose',
      'Cup Holders - Front',
      'Cup Holders - Rear',
      'Bottle Holders - Front Seats',
      'Cargo Tie Down Hooks / Rings',
      'Chrome Interior Door Handles',
      'Centre Courtesy / Dome Light',
      '12V Power Outlet',
      '240V Power Outlet',
      'Ambient Interior Lighting',
      'Rear Privacy Screen',
      'Split-Fold Rear Seats',
      'Flat-Fold Rear Seats',
      'Third Row Seating',
      'Ventilated Boot / Load Area',
    ],
  },
  {
    label: 'Performance & Drivetrain',
    features: [
      '4WD / AWD',
      'Rear-Wheel Drive (RWD)',
      'Front-Wheel Drive (FWD)',
      'Low Range 4WD',
      'Locking Rear Differential',
      'Limited-Slip Differential',
      'Sport Mode',
      'Sport Suspension',
      'Adjustable Suspension',
      'Air Suspension',
      'Launch Control',
      'Sport Exhaust Mode',
      'Carbon Ceramic Brakes',
      'Brembo Brake Upgrade',
    ],
  },
] as const;
